version: '3.9'
services:
  peerjs:
    image: peerjs/peerjs-server:latest
    container_name: peerjs
    ports:
    - 443:9000
    command:
    - --port=9000
    - --path=/myapp
    - --allow_discovery=true